#!/bin/sh
set -e

: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"

: "${POSTGRES_MIGRATION_USERNAME:?POSTGRES_MIGRATION_USERNAME is required}"
: "${POSTGRES_MIGRATION_PASSWORD:?POSTGRES_MIGRATION_PASSWORD is required}"

: "${POSTGRES_APPLICATION_USERNAME:?POSTGRES_APPLICATION_USERNAME is required}"
: "${POSTGRES_APPLICATION_PASSWORD:?POSTGRES_APPLICATION_PASSWORD is required}"

psql -v ON_ERROR_STOP=1 \
	--username "$POSTGRES_USER" \
	--dbname "$POSTGRES_DB" <<-EOSQL

CREATE ROLE ${POSTGRES_MIGRATION_USERNAME}
WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOREPLICATION
	NOBYPASSRLS
	PASSWORD '${POSTGRES_MIGRATION_PASSWORD}';

CREATE ROLE ${POSTGRES_APPLICATION_USERNAME}
WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOREPLICATION
	NOBYPASSRLS
	PASSWORD '${POSTGRES_APPLICATION_PASSWORD}';

CREATE DATABASE itmp_shadow
OWNER ${POSTGRES_MIGRATION_USERNAME};

REVOKE ALL ON DATABASE ${POSTGRES_DB} FROM PUBLIC;
REVOKE TEMPORARY ON DATABASE ${POSTGRES_DB} FROM PUBLIC;

REVOKE ALL ON DATABASE itmp_shadow FROM PUBLIC;
REVOKE TEMPORARY ON DATABASE itmp_shadow FROM PUBLIC;

REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT ON DATABASE template0 FROM PUBLIC;
REVOKE CONNECT ON DATABASE template1 FROM PUBLIC;

GRANT CONNECT ON DATABASE ${POSTGRES_DB}
TO ${POSTGRES_MIGRATION_USERNAME};

GRANT CONNECT ON DATABASE ${POSTGRES_DB}
TO ${POSTGRES_APPLICATION_USERNAME};

GRANT CONNECT ON DATABASE itmp_shadow
TO ${POSTGRES_MIGRATION_USERNAME};

ALTER SCHEMA public OWNER TO ${POSTGRES_MIGRATION_USERNAME};

REVOKE ALL ON SCHEMA public FROM PUBLIC;

GRANT ALL ON SCHEMA public
TO ${POSTGRES_MIGRATION_USERNAME};

GRANT USAGE ON SCHEMA public
TO ${POSTGRES_APPLICATION_USERNAME};

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO ${POSTGRES_APPLICATION_USERNAME};

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO ${POSTGRES_APPLICATION_USERNAME};

ALTER DEFAULT PRIVILEGES
FOR ROLE ${POSTGRES_MIGRATION_USERNAME}
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES
TO ${POSTGRES_APPLICATION_USERNAME};

ALTER DEFAULT PRIVILEGES
FOR ROLE ${POSTGRES_MIGRATION_USERNAME}
IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES
TO ${POSTGRES_APPLICATION_USERNAME};

EOSQL

psql -v ON_ERROR_STOP=1 \
	--username "$POSTGRES_USER" \
	--dbname "itmp_shadow" <<-EOSQL

ALTER SCHEMA public OWNER TO ${POSTGRES_MIGRATION_USERNAME};

REVOKE ALL ON SCHEMA public FROM PUBLIC;

GRANT ALL ON SCHEMA public
TO ${POSTGRES_MIGRATION_USERNAME};

EOSQL